drop table Person;
drop table Item;

CREATE TABLE Person(
                       id int primary key generated by default as identity,
                       name varchar(100) not null,
                       age int check ( age < 100 )
);

CREATE TABLE Item(
                     id int primary key generated by default as identity,
                     person_id int references  Person(id) on delete set null,
                     item_name varchar(100) not null
);

insert into Person (name, age) values ('person#1', 20);
insert into Person (name, age) values ('person#2', 24);
insert into Person (name, age) values ('person#3', 29);
insert into Person (name, age) values ('person#4', 33);

insert into Item (person_id, item_name) values (1, 'item#1');
insert into Item (person_id, item_name) values (1, 'item#2');
insert into Item (person_id, item_name) values (2, 'item#3');
insert into Item (person_id, item_name) values (3, 'item#4');
insert into Item (person_id, item_name) values (3, 'item#5');
insert into Item (person_id, item_name) values (3, 'item#6');
insert into Item (person_id, item_name) values (4, 'item#7');

select * from Person;
